language: java

sudo: false
dist: trusty

branches:
  except:
  - gh-pages

before_install:
  - unset _JAVA_OPTIONS

install: echo "The default Travis install script is being skipped!"

matrix:
  include:
    # OpenJDK - Java 9
    - env: TARGET='-Pjava9' EXPERIMENTAL='false'
      jdk: openjdk9
    # OpenJDK - Java 10
    - env: TARGET='-Pjava10' EXPERIMENTAL='false'
      jdk: openjdk10
    # OpenJDK - Java 11
    - env: TARGET='-Pjava11' EXPERIMENTAL='false'
      jdk: openjdk11
    # OpenJDK - Java 12
    - env: TARGET='-Pjava11' EXPERIMENTAL='true'
      jdk: openjdk12
    # OpenJDK - Java 13
    - env: TARGET='-Pjava11' EXPERIMENTAL='true'
      jdk: openjdk-ea
    # OpenJ9 - Java 11
    - env: JDK="OpenJ9 11" TARGET='-Pjava11' EXPERIMENTAL='false'
      before_script:
        - . ci/install-jdk.sh -W ~/custom-java --url "https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&type=jdk&heap_size=normal"

script:
  - ./mvnw install ${TARGET} -DskipTests=true -Dmaven.javadoc.skip=true -Dnet.bytebuddy.experimental=${EXPERIMENTAL} -Dnet.bytebuddy.test.ci=true -pl '!byte-buddy-gradle-plugin'
  - ./mvnw jacoco:prepare-agent verify jacoco:report ${TARGET} -Pintegration -Dnet.bytebuddy.experimental=${EXPERIMENTAL} -Dnet.bytebuddy.test.ci=true -pl '!byte-buddy-gradle-plugin'
